### ISSUE TITLE
Rust-analyzer fails to compile anyhow 1.0.61: method `backtrace` is not a member of trait `StdError`

### ISSUE THREAD

**Issue by AKhranovskiy** [dtolnay/anyhow#257] opened 2022-08-12 15:06 UTC
Rust-analyzer in VSCode extensions fails to compile anyhow 1.0.61 due to "method `backtrace` is not a member of trait `StdError`" in many places.

Versions:
rust-analyzer 0.4.1166-standalone (696bee324 2022-08-11)
anyhow 1.0.61
rustc 1.65.0-nightly (20ffea693 2022-08-11) nightly-x86_64-unknown-linux-gnu (default)

**Comment by dtolnay** [comment] 2022-08-12 16:07
Duplicate of #254.

**Closed by dtolnay** 2022-08-12 16:07 UTC
