### ISSUE TITLE
`#![feature]` may not be used on the stable release channel error reappears in latest version 1.0.66

### ISSUE THREAD

**Issue by fishseabowl** [dtolnay/anyhow#286] opened 2022-12-05 19:30 UTC
When I use anyhow-1.0.66, I get the following error:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
   -->.../anyhow-1.0.66/src/lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> .../anyhow-1.0.66/src/lib.rs:214:61
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                                             ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `anyhow` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

```
rustc version: rustc 1.65.0 (897e37553 2022-11-02)
anyhow="1.0.66"
```

Also, anyhow-1.0.60 works fine.

**Comment by dtolnay** [comment] 2022-12-05 19:36
This is a duplicate of #250.

**Closed by dtolnay** 2022-12-05 19:36 UTC
