### ISSUE TITLE
anyhow `v1.0.66` leaks some nightly flags

### ISSUE THREAD

**Issue by sassman** [dtolnay/anyhow#289] opened 2022-12-13 18:27 UTC
with anyhow `v1.0.66` on:
```sh
❯ cargo --version && rustc --version
cargo 1.65.0 (4bc8f24d3 2022-10-20)
rustc 1.65.0 (897e37553 2022-11-02)
```

I get the following errors:
```raw
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.66/src/lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/d34dl0ck/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.66/src/lib.rs:214:61
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                                             ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `anyhow` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

PS: `cargo +nightly test` does not lead to the error above.

**Comment by dtolnay** [comment] 2022-12-13 20:07
Duplicate of #250.

**Closed by dtolnay** 2022-12-13 20:07 UTC

**Comment by blueglyph** [comment] 2023-01-07 14:40
Good to know, I have this problem each time I checkout and build a project based on `anyhow`. 😅
