### ISSUE TITLE
Nightly feature wrongly enabled on stable toolchain

### ISSUE THREAD

**Issue by i509VCB** [dtolnay/anyhow#326] opened 2023-11-07 02:21 UTC
It appears that I get this error when building Smithay on a stable toolchain:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/i509vcb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thiserror-1.0.50/src/lib.rs:238:50
    |
238 | #![cfg_attr(error_generic_member_access, feature(error_generic_member_access))]
    |
```

`rustc --version`
```rustc 1.73.0 (cc66ad468 2023-10-03) (Fedora 1.73.0-1.fc38)```

`cargo --version`
```cargo 1.73```

**Comment by dtolnay** [comment] 2023-11-07 02:38
Looks like a duplicate of #250. Most often this has been an IDE bug.

**Closed by dtolnay** 2023-11-07 02:38 UTC

**Comment by i509VCB** [comment] 2023-11-07 02:48
The odd thing is this occurs in a `cargo build`

**Comment by dtolnay** [comment] 2023-11-07 02:57
If there is a reliable sequence of steps to reproduce it that does not involve an IDE, I can take a look. If the only possible way to reproduce it involves an IDE in some way (even if the failed build is a command-line Cargo invocation) then that is an IDE bug. Buggy IDEs corrupt Cargo's `target` directory in a way that causes that behavior.
