### ISSUE TITLE
Support automatic tagging of errors with location?

### ISSUE THREAD

**Issue by kevinushey** [dtolnay/anyhow#278] opened 2022-10-20 16:47 UTC
This is somewhat related to the existing backtrace support. For user-facing application logs, it's useful to log two locations:

1. Where the error itself was logged,
2. Where the error object itself was created.

Right now, the second point is caught in the backtrace, but it'd be useful if we could pull out just the location where the error object itself was constructed (as opposed to the whole stack).

There was some discussion in https://github.com/dtolnay/anyhow/issues/22 around handling this is user code via e.g. an extension trait, but it would be helpful if this could be part of the default behavior -- that is, any error object converted to `anyhow::Result<>` via `?` could automatically be tagged with an error location (if backtraces are enabled), and users could decide whether to include that error location when logging those errors.

(In theory, users of anyhow could post-process the backtrace message and figure out which line is relevant, but I'm hoping there's some tooling in the `backtrace` crate that would make it easier to do when the trace itself is constructed.)

**Comment by dtolnay** [comment] 2022-11-06 12:35
Duplicate of #139.

**Closed by dtolnay** 2022-11-06 12:35 UTC
