### ISSUE TITLE
1.0 doesn't compile in stable channel

### ISSUE THREAD

**Issue by kkolyan** [dtolnay/anyhow#282] opened 2022-11-06 11:47 UTC
Cargo.toml:
```
[package]
name = "bug"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
```
main.rs:
```rust
fn main() {
    println!("Hello, world!");
}
```
action:
```
cargo build
```
output:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\kkolyan\.cargo\registry\src\github.com-1ecc6299db9ec823\anyhow-1.0.66\src\lib.rs:214:32
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\kkolyan\.cargo\registry\src\github.com-1ecc6299db9ec823\anyhow-1.0.66\src\lib.rs:214:61
    |
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\kkolyan\.cargo\registry\src\github.com-1ecc6299db9ec823\anyhow-1.0.66\src\lib.rs:214:61
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access, provide_any))]
    |                                                             ^^^^^^^^^^^

```

**Comment by dtolnay** [comment] 2022-11-06 12:23
Duplicate of #250.

**Closed by dtolnay** 2022-11-06 12:23 UTC
