### ISSUE TITLE
Anhow Doesn't compile

### ISSUE THREAD

**Issue by reji-zero** [dtolnay/anyhow#291] opened 2023-01-10 04:50 UTC
![image](https://user-images.githubusercontent.com/62601155/211464498-9bd31b38-88a4-4540-801d-3585a7f0515c.png)
I was trying to run my code when I had an error mentioning that anyhow was using unstable features and recommended me to use the nightly compiler/

rust-c version: rustc 1.66.0 (69f9c33d7 2022-12-12)

**Comment by reji-zero** [comment] 2023-01-10 04:51
![image](https://user-images.githubusercontent.com/62601155/211464758-17091bc7-2be0-4173-99fc-3bfe8e40bd5f.png)
My dependencies

**Comment by dtolnay** [comment] 2023-01-10 05:00
Duplicate of #250.

**Closed by dtolnay** 2023-01-10 05:00 UTC
