### ISSUE TITLE
Should there be an `impl std::error::Error for anyhow::Error`?

### ISSUE THREAD

**Issue by nathan-at-least** [dtolnay/anyhow#274] opened 2022-09-21 15:51 UTC
When `anyhow::Error` is an associated type of a trait, such as `TryFrom`, then calling code cannot propagate the inner `anyhow::Error` into an outer `anyhow::Error` generically, as [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d86a7e7da19ef81ef3c35a2b6224d844) demonstrates.

In my project I initially thought I could just make the bound precise to `anyhow::Error`, like this:

```
fn do_stuff<T>(arg: T) -> anyhow::Result<()>
  where Thingy: TryFrom<T, Error=anyhow::Error>,
```

-but this precludes other impls that I _do_ want to cover generically, including `impl TryFrom<Thingy> for Thingy` which has `Error = Infallible`. (I'm not sure if this is from a blanket impl in `std` or a dependency I'm using to define `Thingy`.)

-so I attempt to specify all of the `anyhow::Error` construction constraints: 

```
fn do_stuff<T>(arg: T) -> anyhow::Result<()>
  where
    Thingy: TryFrom<T>,
    <Thingy as TryFrom<T>>::Error: 'static + Send + Sync + std::error::Error,
```

Now I can pass any `T` with any `TryFrom` error that can be converted to an `anyhow::Error`. Great!

…except `anyhow::Error` does _not_ implement `std::error::Error`, so it cannot wrap itself.

Is this simply a bug, or is there a design rational for not providing `impl std::error::Error for anyhow::Error` ?

**Comment by dtolnay** [comment] 2022-09-21 19:57
Duplicate of #136.

`Into<anyhow::Error>` is probably the trait bound you are looking for.

**Closed by dtolnay** 2022-09-21 19:57 UTC
